/**
 * Generate TypeScript types from schemas/*.schema.json into packages/domain/src/generated (AGENTS.md rule 3:
 * schemas are contracts; types are generated, never hand-forked). `--check` fails when the committed output is
 * stale, which CI runs so schema and code cannot drift.
 */
import { compile, type JSONSchema } from 'json-schema-to-typescript';
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMAS = join(ROOT, 'schemas');
const OUT = join(ROOT, 'packages', 'domain', 'src', 'generated');
const BASE = 'https://yeonjae.studio/schemas/';

const check = process.argv.includes('--check');

function pascal(name: string): string {
  return name
    .replace(/\.schema\.json$/, '')
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

async function main(): Promise<void> {
  const files = readdirSync(SCHEMAS)
    .filter((f) => f.endsWith('.schema.json'))
    .sort();
  const byId = new Map<string, JSONSchema>();
  for (const f of files) {
    byId.set(BASE + f, JSON.parse(readFileSync(join(SCHEMAS, f), 'utf8')) as JSONSchema);
  }
  const header =
    '/* eslint-disable */\n' +
    '// GENERATED by tools/gen-types.ts from schemas/*.schema.json — do not edit. Run `pnpm gen:types`.\n';
  const outputs = new Map<string, string>();
  const manifest: Record<string, string> = {};
  for (const f of files) {
    const schema = byId.get(BASE + f);
    if (!schema) throw new Error(`schema not loaded: ${f}`);
    const ts = await compile(schema, pascal(f), {
      bannerComment: header,
      cwd: SCHEMAS,
      declareExternallyReferenced: true,
      additionalProperties: false,
      strictIndexSignatures: true,
      unreachableDefinitions: true,
      format: true,
      style: { printWidth: 100, singleQuote: true, trailingComma: 'all', semi: true },
      $refOptions: {
        resolve: {
          yeonjae: {
            order: 1,
            canRead: /^https:\/\/yeonjae\.studio\/schemas\//,
            read: (file: { url: string }) => {
              const s = byId.get(file.url.split('#')[0] ?? '');
              if (!s) throw new Error(`unresolvable $ref ${file.url}`);
              return JSON.stringify(s);
            },
          },
        },
      },
    });
    const outName = f.replace(/\.schema\.json$/, '.ts');
    outputs.set(outName, ts);
    manifest[f] = createHash('sha256')
      .update(readFileSync(join(SCHEMAS, f)))
      .digest('hex');
  }
  const index =
    header +
    files
      .map((f) => {
        const mod = f.replace(/\.schema\.json$/, '');
        return `export * as ${pascal(f)}Schema from './${mod}.js';`;
      })
      .join('\n') +
    '\n';
  outputs.set('index.ts', index);
  outputs.set('schema-manifest.json', JSON.stringify(manifest, null, 2) + '\n');

  if (check) {
    let stale = false;
    for (const [name, content] of outputs) {
      const p = join(OUT, name);
      if (!existsSync(p) || readFileSync(p, 'utf8') !== content) {
        console.error(`stale generated file: packages/domain/src/generated/${name}`);
        stale = true;
      }
    }
    if (stale) {
      console.error('Generated types are out of date. Run `pnpm gen:types` and commit the result.');
      process.exit(1);
    }
    console.log(`generated types are fresh (${files.length} schemas)`);
    return;
  }
  mkdirSync(OUT, { recursive: true });
  for (const [name, content] of outputs) writeFileSync(join(OUT, name), content);
  console.log(
    `wrote ${outputs.size} files to packages/domain/src/generated (${files.length} schemas)`,
  );
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
