#!/usr/bin/env bash
set -eo pipefail
# Unset all live provider and external environment variables
unset YEONJAE_PROVIDER_MODE YEONJAE_NOTION_URL YEONJAE_NOTION_TOKEN YEONJAE_NOTION_TIMEOUT_MS YEONJAE_NOTION_MODEL YEONJAE_MODEL_NOTION
unset YEONJAE_GENSPARK_URL YEONJAE_GENSPARK_TOKEN YEONJAE_GENSPARK_TIMEOUT_MS YEONJAE_GENSPARK_MODEL
unset ANTHROPIC_API_KEY OPENAI_API_KEY GEMINI_API_KEY
# Point to local sandbox DB
export DATABASE_URL="postgres://yeonjae:sigma@127.0.0.1:5432/yeonjae_test"
export DATABASE_MIGRATION_URL="$DATABASE_URL"
exec "$@"
